### ISSUE TITLE
실행 아예 불가능

### ISSUE THREAD

**Issue by Coldlapse** [tmo-gg/War3Buddy#1]
프로그램을 먼저 실행하고 워크래프트 리포지드 실행 시, 프로그램이 강종됩니다.
프로그램을 실행하지 않고 워크래프트 리포지드 실행 시, 프로그램이 실행되지 않습니다.

같은 환경에서 워크래프트 프로즌 스론(클래식) 실행시 아무 이상없이 잘 작동했습니다.

프로젝트를 델파이로 실행후 디버거를 킨 상태에서 해당 이슈 발생 시,
c0000005 access violation
이라는 예외가 디버거에 반환되었습니다.

윈도우 10 Pro 64비트

**Comment by leehoegyu** [comment]
access violation 처음 나오는건 의도된 익셉션입니다. 아마 Deobfuscate 과정에서 문제가 생기는 걸텐데 처리해두지 않은 난독화 패턴 때문에 그럴겁니다. 리포지드 Obfuscated 부분 덤프해서 올려주시면 패치해드리겠습니다

**Comment by Coldlapse** [comment]
Project War3Buddy.exe raised exception class $C0000005 with message 'c0000005 ACCESS_VIOLATION'.


000002735FC000AE 0F1F840000000000 nop dword ptr [rax+rax+$0000]
000002735FC000B6 A92F612DF8       test eax,$f82d612f
000002735FC000BB 81EA09F55A04     sub edx,$045af509
000002735FC000C1 80E9B0           sub cl,$b0
000002735FC000C4 81EFEE8C1EE4     sub edi,$e41e8cee
000002735FC000CA 0F31             rdtsc
000002735FC000CC C7C64D28EAB7     mov esi,$b7ea284d
000002735FC000D2 80EE1B           sub dh,$1b
000002735FC000D5 80C630           add dh,$30
000002735FC000D8 C1A29FC5BD488B   shl dword ptr [rdx+$48bdc59f],$8b
000002735FC000DF 411048B9         adc [r8-$47],cl
000002735FC000E3 AB               stosd
000002735FC000E4 84C7             test bh,al
000002735FC000E6 2BE1             sub esp,ecx
000002735FC000E8 C23228           ret $2832

어느 부분을 어떻게 덤프해달라는건지 잘 모르겠어서.. 일단 Break 찍고 나온 인스트럭션 올립니다.
혹시 다른게 필요하신거면 뭐가 필요하고 어떻게 덤프 가능한지 말씀해주시면 그대로 해보겠습니다.

**Comment by Coldlapse** [comment]
Memory dump loaded successfully. Size: 1024 bytes
48 89 7C 24 18 48 8B 02 4C 8B C1 48 8B 3C 24 48  
B9 AD 12 1E AF 84 0B CB A0 48 8D 04 41 48 89 02  
48 B8 00 10 66 D6 F7 7F 00 00 48 89 44 24 08 48  
B8 36 4D 7B D8 F7 7F 00 00 48 89 44 24 10 48 8B  
44 24 08 48 3B F8 0F 82 E4 00 00 00 48 8B 44 24  
10 48 3B F8 0F 87 D6 00 00 00 80 7F FE FF 41 B9  
01 00 00 00 0F 94 C1 80 7F FD FF 0F 94 C0 0A C8  
80 7F FC FF 0F B6 D1 41 0F 44 D1 80 7F FA FF 0F  
94 C0 0A D0 80 7F FB E8 0F B6 CA 41 0F 44 C9 80  
7F F9 FF 0F 94 C0 0A C8 0F 84 92 00 00 00 66 90
F7 C0 B6 A0 9E 78 C0 EA 00 73 24 81 EF 37 7D 35
BF 83 C2 D0 6A B8 C6 C0 7E C6 C2 BA 80 C3 F1 83
C2 92 C7 C5 CA 1C 17 E2 81 EE 63 C5 60 0E B8 65
48 8B 0C 25 60 00 00 00 0F 1F 84 00 00 00 00 00
A9 2F 61 2D F8 71 28 81 EA 09 F5 5A 04 80 E9 B0
81 EF EE 8C 1E E4 0F 31 0F 88 8C 69 01 00 C7 C6
4D 28 EA B7 80 EE 1B 80 C6 30 C1 A2 9F C5 BD 48
8B 41 10 48 B9 AB 84 C7 2B E1 C2 32 28 49 33 00
48 8B 7C 24 18 48 33 C1 49 89 00 C3 0F 1F 40 00
72 2D 86 ED 73 29 80 C3 EE E8 1E 33 00 00 C6 C7
F4 C6 C0 38 57 81 EF 69 91 24 84 0F 8B 62 C6 01
00 0F 85 23 C3 01 00 81 C6 90 75 BD C0 28 A4 65
48 8B 14 25 60 00 00 00 0F 1F 84 00 00 00 00 00
48 8B FA 33 C0 B9 00 10 00 00 F3 AA 0F 1F 40 00 
F9 C0 E6 00 76 29 83 C1 9B E8 BF 67 00 00 80 EF
35 83 C6 14 81 EB 20 62 F8 5D 81 C0 D3 C4 E2 58
E8 9B AB 01 00 83 C6 F5 0F 31 4E C0 BB 8B 99 EB
BF 2A 12 68 ED 7D E5 5C 09 31 1E 90 22 05 0F 47
6C 44 7D 50 16 92 4E C1 98 94 0B 91 47 BC 08 94
D6 BC C7 04 BA 1F 80 B8 A5 4B AC C7 00 41 13 11
4E 24 38 72 CB 7F 52 CF 32 CC B5 25 6A 10 93 7F
53 73 20 AB DC 4B 1E A6 8E 18 99 E1 49 BD C6 94
16 13 34 AB 52 12 94 5A A7 2A 02 38 0F 4C F0 75
02 59 1F DB FD A0 89 67 53 B7 38 EB D6 48 99 77
0C 19 5F AD 13 98 F5 2E 8C 2A 84 6B E1 26 87 76
DF F1 44 84 D8 D9 8C D6 01 60 5B F4 EE AD 5D E6
90 C7 B7 CC C4 D2 DB 11 71 83 04 C9 93 49 91 21
E5 C1 A8 A8 CA F9 69 0A 78 F8 48 EC 4A 55 2C BA
EC 19 0D 03 10 A4 31 9A 86 FB 78 A1 EC A5 E9 64
12 C8 EE 32 9D 3E EE 8B 44 74 98 FA 35 B8 E2 F7
0D DF 5E 01 DF 4A D0 4A 1A 62 B6 48 A6 30 24 82
8C D6 15 02 F5 6D DE 8A 6C D5 3B 5D B3 B5 35 7B
3D 6D 08 3D C7 58 AA 79 91 80 47 FE EC 6B 07 AE
29 87 27 CF C7 3C A1 DC CA EF 73 76 A2 27 DC 75
F5 C0 4B 59 B6 FA F4 E6 CE 30 8D 6B 7E 74 99 E7
40 40 5F 33 B3 8A BB EF CF 2C EE F4 C4 23 8A B6
47 65 9C 30 14 89 23 2C A8 BF AF 18 C7 29 ED D5
A4 3F 89 FE FA 10 9A 9C 61 AC F9 9D 4F BA 5C 52
9D 98 D6 EE B3 52 4A D9 A0 EF 2E 41 2A 60 E3 26
4C FA D8 AC DD C1 A2 FF 70 AC 27 E0 DC 40 11 CF
98 57 6D F7 38 6C 0D 0A 3F B1 5D BD B2 12 F1 6A
99 29 45 FB A7 6A DA 24 0D F0 9C 78 DF 22 B1 8A
9A 96 D1 12 9D 99 E2 2B 83 BB 5F F5 5B 63 32 47
09 24 E7 68 CB BB 7C 7D A9 7E 69 5B 3C A5 4F 57
F5 47 AA A8 C1 71 92 2D 9A D1 54 26 3C 61 A2 7F
72 33 05 49 7E 50 47 43 C0 58 98 04 5A AE 9F 3C
3E 42 F4 04 B2 25 E6 59 02 3B 48 2D 8E 42 8B 01
2A 69 93 58 D0 CC 6F 1A BB 74 63 30 CD FF 35 1C
44 53 66 AE 9D 62 C1 7D 8B D7 9C 79 27 CE AF 5D
18 2A 14 86 31 89 4F 91 51 D6 4C 00 DF 37 88 FA
4E A1 85 F2 35 F0 0F DB F1 1E B3 0E 23 BA 70 C9
21 00 4D 4F 4A 32 E1 23 4E EF C9 D1 7C 69 15 DB
B1 93 34 5E B9 E1 66 E2 D3 CF 77 1F 3F 41 42 12
28 00 41 CD B4 0F 62 CB 61 61 1B 80 CF 42 CD 4C

제가 적절하게 처리한건지 모르겠네요.

```
procedure DumpMemoryToFile(Data: Pointer; Size: SIZE_T; const FileName: string);
var
  FileStream: TFileStream;
begin
  FileStream := TFileStream.Create(FileName, fmCreate);
  try
    FileStream.WriteBuffer(Data^, Size);
  finally
    FileStream.Free;
  end;
end;
```

으로 메모리 덤핑 프로시저를 War3.Reforged 내에 만들어둔 뒤

```
// 메모리 덤프를 파일로 저장
  DumpMemoryToFile(Data, $400, 'MemoryDump.bin');
```

해당 코드를 Read()문 뒤에 넣어 실행하고 생성된 파일 내용물입니다..

**Comment by Coldlapse** [comment]
덤으로, UI의 캐릭터 아이콘들이 전부 소실되었는데 의도하신건지, 의도하신거라면 기존의 에셋들을 배포하실 생각은 없으신지 여쭙습니다. 제가 파스칼을 잘 모르긴 하는데.. 코드를 보니까 UI 자체가 웹 사이트랑 연동되는 것으로 보이고 https://github.com/tmo-gg/static.tmo.gg/blob/main/ord-helper/assets.json
의 에셋들이 전부 404가 뜨는게 확인되네요

**Comment by Coldlapse** [comment]
답변 및 이슈 대응 감사드립니다.
