### ISSUE TITLE
리포지드 1.36.2.21228 이후 Access violation

### ISSUE THREAD

**Issue by Coldlapse** [tmo-gg/War3Buddy#2]
![image](https://github.com/tmo-gg/War3Buddy/assets/25694445/5ce8bb3c-82cf-4569-9789-e889fc4e2e8a)

최신 버전 업데이트 이후 위 오류가 발생합니다.

**Comment by Coldlapse** [comment]
Memory dump loaded successfully. Size: 1024 bytes
48 89 7C 24 18 48 8B 02 4C 8B C1 48 8B 3C 24 48  
B9 5B F1 D0 A8 67 11 E4 50 48 D1 C0 48 33 C1 48  
89 02 48 B8 00 10 5C 1C F6 7F 00 00 48 89 44 24  
08 48 B8 06 DC 72 1E F6 7F 00 00 48 89 44 24 10  
48 8B 44 24 08 48 3B F8 0F 82 C2 00 00 00 48 8B  
44 24 10 48 3B F8 0F 87 B4 00 00 00 80 7F FE FF  
41 B9 01 00 00 00 0F 94 C1 80 7F FD FF 0F 94 C0  
0A C8 80 7F FC FF 0F B6 D1 41 0F 44 D1 80 7F FA  
FF 0F 94 C0 0A D0 80 7F FB E8 0F B6 CA 41 0F 44  
C9 80 7F F9 FF 0F 94 C0 0A C8 74 74 0F 1F 40 00  
73 1E 8A ED 72 1A 80 E8 B4 C7 C1 8F 9F 84 5B 83  
C5 3D 6A AB E8 B7 59 01 00 6A F1 4A 81 A5 E7 55
65 48 8B 0C 25 60 00 00 00 0F 1F 80 00 00 00 00
F8 8A ED 73 1B 81 ED 36 E1 17 88 83 C1 B2 81 E8
40 22 19 DB C7 C1 CC 4A BD 6A 69 A0 03 DF 96 8B
48 8B 41 10 48 B9 A4 0E 2F 57 98 EE 1B AF 49 33
00 48 8B 7C 24 18 48 33 C1 49 89 00 C3 0F 1F 00
7F 1E 7E 1C 0F 84 CE E0 01 00 81 E9 34 75 16 09
81 E8 21 4E 1E 75 C6 C0 BE C6 C3 AE C1 B0 CD 75
65 48 8B 14 25 60 00 00 00 0F 1F 80 00 00 00 00
48 8B FA 33 C0 B9 00 10 00 00 F3 AA 0F 1F 40 00
7E 1E C0 E1 00 7F 19 81 E9 91 43 99 26 83 C2 78 
57 C6 C6 02 83 C2 C3 75 F8 83 C5 46 4A 69 BA 6F
EB CE FF 8B 41 92 84 93 3B 2E 8D 25 22 94 75 B0
F6 C4 A8 1E A7 22 D5 A1 09 31 25 13 A5 4A 68 EF
DF 3C B1 BA 32 2F 9D EB B3 64 93 59 15 D7 01 6F
34 7F 88 04 58 50 97 D3 0F 38 C4 FC E7 A7 6E 2A
08 90 A4 4C D0 E3 68 38 54 85 A5 6C D3 8D B7 B7
DD 54 6A 14 CD E7 2D 8D 6C BD 56 BB A2 3C 86 0E
8C D5 8B 34 D9 44 57 9D 2F FF 6E 26 44 5D 49 42
4A 47 25 89 A4 9B 74 FE BD D3 B1 C6 CF C0 E9 B3
B3 25 FA 0F 7A 36 1C D5 F6 5D 95 7F FB E7 25 C6
C8 45 70 4B C5 8A 32 99 2D 4C 71 FC 42 B5 7C AF
E8 0B CA 82 80 4E 26 84 42 46 82 A8 83 6D D1 23
F5 12 65 27 07 89 BA 7E 15 E9 1F 01 03 8E B5 84
90 E1 D2 27 A4 C3 AB 7B 79 F5 4D AB 51 13 F9 E6
62 91 4C 44 47 70 E1 D4 35 E8 3D 10 02 50 E2 AB
F5 7B 78 01 B8 DC 48 40 D8 3D A2 1C 5C 60 94 FD
A7 C0 76 FC 99 2B 61 8F 6E B7 9B 58 53 CA D8 8D
58 50 31 D2 B5 82 67 AF 96 7C D3 0F 5F 9F 0C 5F
14 39 48 7D 3E 35 84 F1 60 2A 42 83 F5 44 67 E6
99 3D E0 6E CE 62 A8 A7 68 09 B6 98 EA D0 AC 88
49 55 BC 9B B5 9E 67 A5 D3 E3 8B EC 84 45 AA 25
E5 FA D6 7A C6 E9 CC 46 A8 A4 54 64 45 0F 72 3B
13 E1 24 2C C7 D0 C0 49 6A FD A3 4E E2 8D 2B FA
1C 6B DA 0A A5 A0 A1 BE D7 00 DA 94 CD 37 A8 18
F7 8B 97 E5 87 2B 41 8E B1 B5 7F 3D 04 0F BE 55
29 30 E4 B5 6E 46 C0 19 67 CF 35 40 DE EB 68 7C
2A CC 99 5C 96 72 96 A9 A4 35 7E 63 6C 60 62 20
F4 58 DE A3 7A 6E DB B4 AE BE 4F 7D 54 22 D7 F9
3B AF 31 06 72 7B BA 69 31 7A FF 27 F7 28 98 DC
72 7F 1F 56 02 F9 76 4D 7E E2 A2 B7 CA 9A 2C 6B
2E 26 E7 D9 07 20 12 4A 82 8F 26 A2 90 44 55 16
F4 FE 2F 26 4F 32 F4 41 33 6E 8A 01 A3 74 1B 62
35 9C A3 4B 8E 06 BF ED B0 CD 32 A6 D2 41 5B 59
1F 0A B9 37 59 06 5A 67 57 80 2F 0C 33 8F 3E F4
F5 14 85 D9 16 8D C4 66 AD 19 1B F6 9C ED 7C A9
5E 0A 97 FC DE F5 7D 1A 47 31 D6 8C 61 AA 36 21
13 57 DC 4E D9 3D 03 38 25 3F 8C FD 45 66 06 5D
60 5F 3B 2F 54 D2 68 05 10 62 3D 95 6C 8C CF 52
97 2B 89 26 83 B2 4D A2 B3 EF 0D 79 57 6A 75 A2
51 1A 3E F1 15 DC 20 F1 B8 10 88 11 93 71 C8 F5
7F EB 46 1C BB 0A BB 91 2F 59 24 13 44 CD E7 7D
76 79 0C C6 9C AC 64 CC 49 57 C7 99 52 34 9A 7B

마찬가지로 메모리 덤프를 뜬 결과입니다.
혹시 이러한 문제가 발생할 때 대응할 수 있는 메뉴얼이라던가 방법론을 알려주시면 제가 수정해서 기여할 수도 있을거 같습니다만,,

**Comment by leehoegyu** [comment]
@Coldlapse Deobfuscate 과정에서 나타나는 익셉션은 아닌것으로 보입니다

**Comment by Coldlapse** [comment]
![image](https://github.com/tmo-gg/War3Buddy/assets/25694445/6b594915-0cad-4cb3-b115-f018b55538d9)

21230 패치 이후에 시도해도 마찬가지네요..

메인 컴퓨터 사양:
![image](https://github.com/tmo-gg/War3Buddy/assets/25694445/f54f4c4e-453d-4ed2-b0dd-3a192b7fd006)


서브 컴퓨터에 깔아서 동일 계정으로 시도해도 마찬가지였습니다.
메인 컴퓨터, 서브 컴퓨터 모두에 다른 잘 되는 계정(지인 계정입니다) 을 받아 해당 계정으로 로그인하여 시도해도 마찬가지였습니다.

제 지인분은 프로그램 사용이 원활하다는데... 왜 저만 이런지 모르겠네요.

**Comment by Coldlapse** [comment]
![image](https://github.com/tmo-gg/War3Buddy/assets/25694445/4ac09907-c315-4895-a537-6b25f6fada87)

Memory dump loaded successfully. Size: 1024 bytes
48 89 7C 24 18 48 8B 02 4C 8B C1 48 8B 3C 24 48  
B9 FA 29 1A 16 23 8C 7D E3 48 8D 04 41 48 89 02  
48 B8 00 10 03 26 F7 7F 00 00 48 89 44 24 08 48  
B8 D6 FF 13 28 F7 7F 00 00 48 89 44 24 10 48 8B  
44 24 08 48 3B F8 0F 82 24 01 00 00 48 8B 44 24  
10 48 3B F8 0F 87 16 01 00 00 80 7F FE FF 41 B9  
01 00 00 00 0F 94 C1 80 7F FD FF 0F 94 C0 0A C8  
80 7F FC FF 0F B6 D1 41 0F 44 D1 80 7F FA FF 0F  
94 C0 0A D0 80 7F FB E8 0F B6 CA 41 0F 44 C9 80  
7F F9 FF 0F 94 C0 0A C8 0F 84 D2 00 00 00 66 90  
85 FA C0 E4 00 71 49 F6 DD 68 B5 69 DD 44 0F 8E  
5E BC 01 00 83 C2 DB 81 C5 B2 0D 74 C7 6A B6 75  
84 E8 15 B7 01 00 0F 8A D1 9B 00 00 5A 80 EA 6F  
80 C6 47 81 EE DF CB B5 E4 83 C6 75 0F 83 7A FB
00 00 E8 51 38 01 00 73 01 0F 31 81 81 52 81 02
65 48 8B 0C 25 60 00 00 00 0F 1F 80 00 00 00 00
24 FF 71 4C 0F 87 53 7F 01 00 0F 31 80 E8 75 55
80 E8 D1 0F 86 9F 03 00 00 5E F6 DE E8 F5 81 00
00 56 E8 9D BB 01 00 81 C7 65 D6 77 88 5F 81 C5
E2 43 A9 31 80 C3 C9 80 C2 24 58 E8 D5 B7 00 00
E8 C8 1F 01 00 E8 E2 10 01 00 C1 A6 87 8B 37 6D
48 8B 41 10 48 B9 C8 61 60 5D 9E CE 3D 27 48 8B
7C 24 18 48 C1 C0 09 48 03 C1 49 31 00 C3 66 90
7F 4E C0 FC 00 7E 49 80 C5 0C 80 EB 11 5C 80 C6
D2 73 6D 0F 8D 08 20 01 00 0F 83 A6 79 00 00 0F
85 3C 4B 01 00 E8 4B CA 00 00 81 E8 CF A6 B3 1B
C7 C2 78 64 0F E1 C7 C5 BD BC C5 FE 80 C1 80 81
C0 D7 F4 73 EF 81 E8 DA E2 B0 C8 C0 A9 54 33 05
65 48 8B 14 25 60 00 00 00 0F 1F 80 00 00 00 00
48 8B FA 33 C0 B9 00 10 00 00 F3 AA 0F 1F 40 00 
74 4E 8A E4 75 4A 0F 80 96 2F 01 00 81 EB BD F5
84 58 81 C0 88 CE 29 A7 81 C0 03 00 2B BC E8 99
01 00 00 58 80 C1 F4 80 EF 48 59 80 C1 C8 5E 5D
80 C6 96 C7 C7 F5 DC 33 57 68 D1 14 B3 96 E8 F2
5B 01 00 5B C6 C7 65 F6 DB 0F 8F E7 D1 00 00 BE
EB 9E 1F 76 BA 06 BE A1 2F 9E 14 A4 76 E2 CF 6C
D4 84 A6 BC 41 D6 EB 15 C5 57 8F 35 25 3A BC 7C
9C E1 AF 2C 78 13 00 45 93 2E C5 8C 85 9D 37 D9
C6 1C 7E 6B 01 24 38 9B A6 9B 89 A8 C5 7E 6A EC
71 1E DB BC 84 CF C9 4A DB 0B AA 6D CF 06 87 90
BB 41 3A 9D B0 3A 7F 5C 15 19 EC 52 22 58 38 AB
CF 2E 7A 33 0F E7 AC 4C 47 DF 73 AF 5C 87 71 9C
C2 EC 1B C0 8F 68 C8 6E C3 54 31 D8 8F 15 26 23
24 91 B7 15 37 51 AA 79 0E 82 D4 7E 58 AA A6 29
E8 23 C2 0E 10 60 93 BD E2 E1 A9 C8 EC FA CE 7F
48 5E F4 E0 89 EF D3 27 7C E6 D3 A1 B4 14 8D E3
1F 43 7C 78 64 2A D6 BA 4C DB 0C 87 36 EE D8 E3
47 42 53 7A B7 63 1C E7 4E B0 2D F9 EE 64 DE 89
CC FC 7A 67 36 E8 D0 EA 16 14 E0 3E 93 9B E6 36
2E 95 B7 43 23 46 34 01 9C B6 A8 D9 79 44 46 0F
E4 A2 E5 8F 09 63 88 81 86 2C 26 B7 6A FA DC E8
72 72 B1 B6 3D 9F 7A E4 5A CF 73 C4 14 C8 04 09
E3 AA B1 C9 91 C4 BF D7 82 EF 27 50 33 E4 AA 1D
04 9E 88 DE 9F 5E F9 F8 BD 5E 75 52 C5 94 B6 90
B8 84 C3 FB DC 79 D9 88 69 77 F7 B2 6F 89 BD 56
35 04 97 0A 1A 93 B4 26 4A DE 1F D0 F5 69 17 C5
81 39 E9 68 3D 7E 02 38 87 FE 63 0B 71 47 CB 16
04 02 1F CA 25 1C 7F 17 D3 A1 95 F8 40 FB 41 4F
25 B3 E8 04 B6 B1 C9 CF 99 B2 31 BE 53 85 34 0B
E9 CA 5E 46 63 C4 EE 23 05 C9 07 C4 05 75 58 C2
68 6D 77 8D 50 4B 16 4A 65 97 32 50 C4 63 0A BE
72 8E 95 0D 03 0C 93 D9 6B E7 D9 D0 46 D5 6F 0F
47 61 CF B4 D1 AF 2C 07 27 78 DA 8C 3F 0A 7E FC
F6 79 98 6C 6C AB 3C 3B 0C 1C 41 75 40 1E 08 17



메모리 덤프는 위와 같습니다.

**Comment by leehoegyu** [comment]
@Coldlapse Deobfuscate 함수에 브레이크포인트 거시고 어떻게 작동하는 함수인지 한번 보시는것도 이슈해결에 도움이 되실겁니다.
제가 현재 군복무 중이라 이슈 대응이 힘든 점 양해부탁드립니다.

**Comment by Coldlapse** [comment]
왠지는 모르겠는데 델파이 상에서 디버그 찍고 실행하는것이 아닌 컴파일된 exe파일을 따로 직접 실행하니 잘 작동하네요. release해주신 파일은 또 작동하지 않구요.

업데이트 될때마다 제가 직접 컴파일해서 사용하면 될 것 같습니다. 감사합니다.

![image](https://github.com/tmo-gg/War3Buddy/assets/25694445/c617bae8-325c-47ea-ae49-e3a8e35a3637)


여담으로 아직 복구되지 않은 이미지 리소스가 소수 존재합니다만 여유가 나실 때 이에 대한 복구도 요청드립니다. 특별함에 압살롬도 아직 복구가 안되었네요.

**Comment by changmyeong** [comment]
> 왠지는 모르겠는데 델파이 상에서 디버그 찍고 실행하는것이 아닌 컴파일된 exe파일을 따로 직접 실행하니 잘 작동하네요. release해주신 파일은 또 작동하지 않구요.
> 
> 업데이트 될때마다 제가 직접 컴파일해서 사용하면 될 것 같습니다. 감사합니다.
> 
> ![image](https://private-user-images.githubusercontent.com/25694445/344126197-c617bae8-325c-47ea-ae49-e3a8e35a3637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjI1NzYsIm5iZiI6MTcyMjY2MjI3NiwicGF0aCI6Ii8yNTY5NDQ0NS8zNDQxMjYxOTctYzYxN2JhZTgtMzI1Yy00N2VhLWFlNDktZTNhOGUzNWEzNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA1MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMmVmNDBiY2I4NDAzYTJjYWNmMzc3ZTYyMDU0ZmRlZjc3MjYyN2EzYTZkZTQ4MzczZjAyYjBkZWU2N2VhY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u29TNE3eAx0tT-bUmE6MO3x5eNrmR1e6fhx-uzrI1nw)
> 
> 여담으로 아직 복구되지 않은 이미지 리소스가 소수 존재합니다만 여유가 나실 때 이에 대한 복구도 요청드립니다. 특별함에 압살롬도 아직 복구가 안되었네요.

혹시 웹은 좀 할 줄 아시나요?
프로그램에 웹뷰가 떠있고 유닛 계산하고 이미지를 띄우는건 전부 웹으로 되어 있는데요.

웹 코드를 공개해 드리면 저런 이미지 같은건 고치는 PR을 올려주실 수 있는지 문의를 드립니다.

**Comment by Coldlapse** [comment]
웹같은경우는 잘 몰라도 GPT같은거 활용해서 어떻게든 될거같네요 워낙 널리 알려져있는 분야다보니까
웹도 공개된다면 만약 TMO.GG 측 호스팅같은게 만료되어도 제 서버에서 돌리는쪽으로 변경하여 PR 올릴수 있을거 같습니다.

만약 공개가 이루어진다면 현재 유실되어있는 이미지 리소스도 같이 공개해주시면 감사하겠습니다.

**Comment by changmyeong** [comment]
> 웹같은경우는 잘 몰라도 GPT같은거 활용해서 어떻게든 될거같네요 워낙 널리 알려져있는 분야다보니까 웹도 공개된다면 만약 TMO.GG 측 호스팅같은게 만료되어도 제 서버에서 돌리는쪽으로 변경하여 PR 올릴수 있을거 같습니다.
> 
> 만약 공개가 이루어진다면 현재 유실되어있는 이미지 리소스도 같이 공개해주시면 감사하겠습니다.

서버는 굳이 돈 내거나 하지 않고 github.io를 사용하면 될 것 같아요. 클라이언트만 사용해서요.
그리고 이미지 리소스가 날라간 듯 해서 요청을 드리려고 했던 거라.. ㅠㅠ

tmo.gg 도메인 만료 기한도 끝나버려서 github.io로 이관하는 작업이 필요합니다.

**Comment by Coldlapse** [comment]
아 이미지 리소스가 아예 유실된건가요 그러면 대체제를 찾아야하는 상황인거네요
웹 부분 오픈해주시면 대체제 찾아서 메꿔보겠습니다
